version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/app/api
    ports:
      - "5000:5000"
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
